// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwMUqqmY_IhBRgHzUVD01wc9HQP7S7CGM',
    appId: '1:653765384227:web:2a01c32629d019d634b996',
    messagingSenderId: '653765384227',
    projectId: 'e-hrm-1e3e0',
    authDomain: 'e-hrm-1e3e0.firebaseapp.com',
    storageBucket: 'e-hrm-1e3e0.firebasestorage.app',
    measurementId: 'G-67QZCTNKBW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBimwmKvkInVZjLnEalA78BwoQjxahqhBM',
    appId: '1:653765384227:android:d4821fc6d8b5910c34b996',
    messagingSenderId: '653765384227',
    projectId: 'e-hrm-1e3e0',
    storageBucket: 'e-hrm-1e3e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwKBubnm8fHIe_KqKQr4gAg7jJCwuqpeg',
    appId: '1:653765384227:ios:07d94a69f63d1b4434b996',
    messagingSenderId: '653765384227',
    projectId: 'e-hrm-1e3e0',
    storageBucket: 'e-hrm-1e3e0.firebasestorage.app',
    iosBundleId: 'com.example.eHrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwKBubnm8fHIe_KqKQr4gAg7jJCwuqpeg',
    appId: '1:653765384227:ios:07d94a69f63d1b4434b996',
    messagingSenderId: '653765384227',
    projectId: 'e-hrm-1e3e0',
    storageBucket: 'e-hrm-1e3e0.firebasestorage.app',
    iosBundleId: 'com.example.eHrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwMUqqmY_IhBRgHzUVD01wc9HQP7S7CGM',
    appId: '1:653765384227:web:bf4ca2026ea7050b34b996',
    messagingSenderId: '653765384227',
    projectId: 'e-hrm-1e3e0',
    authDomain: 'e-hrm-1e3e0.firebaseapp.com',
    storageBucket: 'e-hrm-1e3e0.firebasestorage.app',
    measurementId: 'G-M581H0HMMQ',
  );

}