// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHaHOsrtZghC2JAeP53-rtg9gUKUmmMcM',
    appId: '1:584929841793:web:1a1cff15646de867067380',
    messagingSenderId: '584929841793',
    projectId: 'e-hrm-2d3fe',
    authDomain: 'e-hrm-2d3fe.firebaseapp.com',
    storageBucket: 'e-hrm-2d3fe.firebasestorage.app',
    measurementId: 'G-K58K7RVTHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIrD5IY97yGeCMvL15nt2yiJP5b3mBDGA',
    appId: '1:584929841793:android:ba01378f93dd828e067380',
    messagingSenderId: '584929841793',
    projectId: 'e-hrm-2d3fe',
    storageBucket: 'e-hrm-2d3fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2hxPlyI1Cl7hNe-Il8hJSkzd07U1u3zo',
    appId: '1:584929841793:ios:92cf5811e84ff23c067380',
    messagingSenderId: '584929841793',
    projectId: 'e-hrm-2d3fe',
    storageBucket: 'e-hrm-2d3fe.firebasestorage.app',
    iosBundleId: 'com.example.eHrm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2hxPlyI1Cl7hNe-Il8hJSkzd07U1u3zo',
    appId: '1:584929841793:ios:92cf5811e84ff23c067380',
    messagingSenderId: '584929841793',
    projectId: 'e-hrm-2d3fe',
    storageBucket: 'e-hrm-2d3fe.firebasestorage.app',
    iosBundleId: 'com.example.eHrm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHaHOsrtZghC2JAeP53-rtg9gUKUmmMcM',
    appId: '1:584929841793:web:14cf402a4a28c6c7067380',
    messagingSenderId: '584929841793',
    projectId: 'e-hrm-2d3fe',
    authDomain: 'e-hrm-2d3fe.firebaseapp.com',
    storageBucket: 'e-hrm-2d3fe.firebasestorage.app',
    measurementId: 'G-ZJ8F83STR3',
  );
}
